development:
  table_namespace: <%= Jets.config.table_namespace %>
  endpoint: http://localhost:8000

test:
  endpoint: http://localhost:8000
  table_namespace: <%= Jets.config.table_namespace %>

production:
  table_namespace: <%= Jets.config.table_namespace %>
